<?php

/**
 * Implements hook_page_delivery_callback_alter().
 */
function angularjs_page_delivery_callback_alter(&$callback) {
  // pjax requests can be detected by the X-PJAX http header.
  // When serving pjax requests, deliver just the main page content.
  if (!empty($_SERVER['HTTP_X_ANGULARJS']) && $callback == 'drupal_deliver_html_page') {
    $callback = 'angularjs_deliver_page_content';
  }
}

/**
 * Delivers only the main content of the requested page, for pjax requests.
 */
function angularjs_deliver_page_content($page_callback_result) {
  if (is_int($page_callback_result)) {
    // Pass over to drupal_deliver_html_page() to deal with errors.
    drupal_deliver_html_page($page_callback_result);
  }
  else {
    if (is_null(drupal_get_http_header('Content-Type'))) {
      drupal_add_http_header('Content-Type', 'text/html; charset=utf-8');
    }

    // $page_callback_result contains the main contents of the page.
    // Add a page title, which will be picked up and used by pjax.
    $output = '<title>' . drupal_get_title() . '</title>' . render($page_callback_result);
    $output .= drupal_get_js();
    print($output);

    // Make sure the requests are cached. pajax requests will be cached separately
    // from standard page requests thanks to the "_pjax" query string.
    drupal_page_footer();
  }
}

/**
 * Implements hook_library().
 */
function angularjs_library() {
  $libraries = array();
  $library_path = libraries_get_path('angular');

  $js = array(
    $library_path . '/angular.min.js' => array(),
    $library_path . '/angular-resource.min.js' => array(),
    $library_path . '/angular-cookies.min.js' => array(),
    $library_path . '/angular-sanitize.min.js' => array());

  // Load module types exposed by modules
  foreach (array('resources', 'filters', 'directives', 'services') as $type) {
    foreach (angularjs_get_modules($type) as $path => $options) {
      $js[$path] = $options;
    }
  }

  $libraries['angularjs'] = array(
    'title' => 'AngularJS',
    'website' => 'angularjs.org',
    'version' => '1.0.6',
    'js' => $js,
  );

  $libraries['angularjs-bootstrap'] = array(
    'title' => 'AngularJS Bootstrap',
    'website' => 'angularjs.org',
    'version' => '1.0.2',
    'js' => array(
      $library_path . '/angular-bootstrap.min.js' => array(),
    ),
  );

  // Add CSRF token required by restWS.
  $js_settings = array(
    'angularjsApp' => array(
      'restws_csrf_token' => drupal_get_token('restws'),
      'basePath' => url('', array('absolute' => TRUE)),
    ),
  );

  drupal_add_js($js_settings, 'setting');

  return $libraries;
}

/**
 * Initializes an AngularJS application setting the application name, the base path
 * and adds the library
 * 
 * @param string $name
 *   The application name
 *   
 * @param string $base_href
 *   The base href, defaults to current page if nothing is entered
 */
function angularjs_init_application($name, $base_href = NULL) {
  // If no value is entered use the current URL
  if (NULL == $base_href) {
    $base_href = url($_GET['q']) . '/';
  }
  
  angularjs_set_app_name($name);
  angularjs_set_base_href($base_href);
  drupal_add_library('angularjs', 'angularjs');
}

/**
 * Gets the AngularJS application name for the current request / page
 * 
 * @return string
 */
function angularjs_get_app_name() {
  return drupal_static('angularjs_app_name');
}

/**
 * Sets AngularJS application name for the current request / page
 * 
 * @param string $app_name
 *   The application name
 *   
 * @return string
 */
function angularjs_set_app_name($app_name) {
  $name = &drupal_static('angularjs_app_name');
  $name = $app_name;
  
  return $name;
}

/**
 * Gets the current base tag
 * 
 * @return string
 */
function angularjs_get_base_href() {
  return drupal_static('angularjs_base_href');
}

/**
 * Sets the current base tag
 * 
 * @param string $base_href
 *   The base href for the application
 *   
 * @return string
 */
function angularjs_set_base_href($base_href) {
  $href = &drupal_static('angularjs_base_href');
  $href = $base_href;
  
  return $href;
}

/**
 * Implements hook_preprocess_html
 * 
 * Adds <base> tag and sets ng-app attribute if provided
 */
function angularjs_preprocess_html(&$vars) {
  $app_name = angularjs_get_app_name();
  $base_href = angularjs_get_base_href();
  
  if (FALSE === empty($app_name)) {
    $vars['attributes_array']['ng-app'] = $app_name;
  }
  
  if (FALSE === empty($base_href)) {
    drupal_add_html_head(array('#tag' => 'base', '#attributes' => array('href' => $base_href)), 'angularjs_base_href');
  }
}

/**
 * Implements hook_element_info().
 */
function angularjs_element_info() {
  $types['ng_select'] = array(
    '#input' => TRUE,
    '#multiple' => FALSE,
    '#theme' => 'ng_select',
    '#theme_wrappers' => array('form_element'),
    '#process' => array('form_process_select', 'ajax_process_form', 'angularjs_process_select'),
    '#ng_model' => '',
    // @todo: Add option to look at parents(s) for the controller definition.
    '#ng_controller' => '',
    '#attached' => array(
      'library' => array(
        // @todo: Check why this doesn't work.
        // array('angularjs', 'angularjs'),
      ),
    ),
  );

  return $types;
}

/**
 * Implements hook_theme().
 */
function angularjs_theme() {
  return array(
    'ng_select' => array(
      'render element' => 'element',
    ),
    'ng_table' => array(
      'variables' => array(
        'header' => NULL,
        'attributes' => array(),
        'caption' => NULL,
        'sticky' => TRUE,
        'empty' => '',
        // Angular settings.
        'row' => array(),
        'ng_model' => '',
        'ng_controller' => '',
        'ng_repeat' => '',
        'ng_empty' => '',
      ),
    ),
  );
}

/**
 * Process ng-select element.
 */
function angularjs_process_select($element, $form_state) {
  // Pass the option to JS.
  $options = array();
  foreach ($element['#options'] as $value => $name) {
    $options[] = array('value' => $value, 'name' => $name);

  }
  
  if (TRUE === isset($element['#ng_controller'])) {
    $data['angularjs'][$element['#ng_controller']][$element['#ng_model']] = array(
      'options' => $options,
      'required' => $element['#required'],
      'selected' => $element['#default_value'],
      '_type' => 'select',
      '_name' => $element['#name'],
    );
  
    $element['#attached']['js'][] = array(
      'type' => 'setting',
      'data' => $data,
    );
  }
  
  return $element;
}

/**
 * Returns HTML for a ng-select form element.
 *
 * @ingroup themeable
 */
function theme_ng_select($variables) {
  $element = $variables['element'];
  element_set_attributes($element, array('id', 'name', 'size'));
  _form_set_class($element, array('form-select'));

  return '<select' . drupal_attributes($element['#attributes']) . ' ng-model="' . $element['#ng_model'] . '.selected" ng-options="option.value as option.name for option in '. $element['#ng_model'] . '.options"></select> ';
}

/**
 * Returns HTML for a table, using AngularJs.
 */
function theme_ng_table($variables) {
  $header = $variables['header'];
  $row = $variables['row'];
  $attributes = $variables['attributes'];
  $caption = $variables['caption'];
  $sticky = $variables['sticky'];
  $empty = $variables['empty'];

  $ng_controller = $variables['ng_controller'];
  $ng_model = $variables['ng_model'];
  $ng_repeat = !empty($variables['ng_repeat']) ? $variables['ng_repeat'] : "item in $ng_model";
  $ng_empty = !empty($variables['ng_empty']) ? $variables['ng_empty'] : "!$ng_model.length";

  // Add sticky headers, if applicable.
  if (count($header) && $sticky) {
    drupal_add_js('misc/tableheader.js');
    // Add 'sticky-enabled' class to the table to identify it for JS.
    // This is needed to target tables constructed by this function.
    $attributes['class'][] = 'sticky-enabled';
  }

  $output = '<table' . drupal_attributes($attributes) . ">\n";

  if (isset($caption)) {
    $output .= '<caption>' . $caption . "</caption>\n";
  }

  // Add the 'empty' row message if available.
  if (empty($row) && $empty) {
    $header_count = 0;
    foreach ($header as $header_cell) {
      if (is_array($header_cell)) {
        $header_count += 1;
      }
      else {
        $header_count++;
      }
    }
    // @todo: Fix.
    $rows[] = array(array('data' => $empty, 'class' => array('empty', 'message')));
  }

  // Format the table header:
  if (count($header)) {
    // HTML requires that the thead tag has tr tags in it followed by tbody
    // tags. Using ternary operator to check and see if we have any rows.
    $output .= (count($row) ? ' <thead><tr>' : ' <tr>');
    foreach ($header as $cell) {
      $output .= '<th>' . $cell . '</th>';
    }
    // Using ternary operator to close the tags based on whether or not there are rows
    $output .= (count($row) ? " </tr></thead>\n" : "</tr>\n");
  }

  // Format the table rows:
  if (!empty($row)) {
    $output .= "<tbody>\n";

    // Build row
    $output .= ' <tr ng-repeat="' . $ng_repeat . '">';
    foreach ($row as $cell) {
      $output .= '<td>' . $cell . '</td>';
    }
    $output .= " </tr>\n";

    // Add empty-text <tr>.
    $output .= '<tr ng-show="'. $ng_empty . '"><td>' . $empty . '</td></tr>';
    $output .= "</tbody>\n";
  }

  $output .= "</table>\n";

  return $output;
}


/**
 * Returns the registered AngularJS modules
 *
 * @param string $type
 * @param boolean $reset
 * @return array
 */
function angularjs_get_modules($type, $reset = FALSE) {
  $name = 'angularjs_' . $type;

  $modules = &drupal_static($name, array());

  if (TRUE === empty($modules)) {
    $cached_modules = cache_get($name);

    if (FALSE === isset($cached_modules->data) || TRUE == $reset) {
      $modules = module_invoke_all($name);
      drupal_alter($name, $modules);

      cache_set($name, $modules);
    }
    else {
      $modules = $cached_modules->data;
    }
  }

  return $modules;
}

/**
 * Returns a list of AngularJS resources exposed by modules
 *
 * @param boolean $reset
 * @return array
 */
function angularjs_get_resources($reset = FALSE) {
  return angularjs_get_modules('resources', $reset);
}

/**
 * Returns a list of AngularJS filters exposed by modules
 *
 * @param boolean $reset
 * @return array
 */
function angularjs_get_filters($reset = FALSE) {
  return angularjs_get_modules('filters', $reset);
}

/**
 * Returns a list of AngularJS directives exposed by modules
 *
 * @param boolean $reset
 * @return array
 */
function angularjs_get_directives($reset = FALSE) {
  return angularjs_get_modules('directives', $reset);
}

/**
 * Returns a list of AngularJS services exposed by modules
 *
 * @param boolean $reset
 * @return array
 */
function angularjs_get_services($reset = FALSE) {
  return angularjs_get_modules('services', $reset);
}

/**
 * Implements hook_angularjs_resources
 *
 * @return array
 */
function angularjs_angularjs_resources() {
  return array(drupal_get_path('module', 'angularjs') . '/js/angular_resource.js' => array());
}

/**
 * Sends AngularJS template to browser
 *
 * @param string $var
 */
function angularjs_template_output($var) {
  drupal_add_http_header('Content-Type', 'text/html');

  // Add new JS.
  echo drupal_get_js();

  if (isset($var)) {
    echo $var;
  }
}

/**
 * Adds an Angular JS template partial to be sent to the page. Takes either a text
 * template or a render array
 *
 * @param string $name
 * @param mixed $output
 * @return array
 */
function angularjs_add_partial($name = NULL, $output = NULL) {
  $partials = &drupal_static(__FUNCTION__, array());

  if (NULL != $name) {
    $partials[$name] = $output;
  }

  return $partials;
}

/**
 * Implements hook_page_alter
 *
 * Adds partials to the page footer
 *
 * @param array $variables
 */
function angularjs_page_alter(&$variables) {
  $partials = angularjs_add_partial();

  drupal_alter('angularjs_partials', $partials);

  foreach ($partials as $name => $output) {

    // If we have a render array render it
    if (TRUE === is_array($output)) {
      $output = render($output);
    }

    $element = array(
      '#tag' => 'script',
      '#value' => $output,
      '#attributes' => array(
        'type' => 'text/ng-template',
        'id' => $name,
      )
    );

    $variables['footer']['partial_' . $name] = array('#markup' => theme('html_tag', array('element' => $element)));
  }
}
