<?php

/**
 * Implements hook_menu
 * 
 * @return array
 */
function angularjs_examples_menu() {
  $items = array();

  $items['angular/nodes'] = array(
    'title' => t('Nodes'),
    'page callback' => 'angularjs_examples_nodes',
    'access arguments' => array('access content'),
  );
  
  $items['angular/nodes/list'] = array(
    'title' => t('Nodes'),
    'page callback' => 'angularjs_examples_nodes_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback for node list template
 * 
 * @return string
 */
function angularjs_examples_nodes_list() {
  angularjs_template_output(theme('angularjs_examples_nodes_list', array('types' => node_type_get_names())));
}

/**
 * Page callback for node example
 * 
 * @return string
 */
function angularjs_examples_nodes() {
  drupal_add_library('angularjs', 'angularjs');
  drupal_add_js(drupal_get_path('module', 'angularjs_examples') . '/js/nodelist.js');
  
  return theme('angularjs_examples_nodes');
}

/**
 * Implements hook_theme
 * 
 * @return array
 */
function angularjs_examples_theme() {
  $themes = array();

  $themes['angularjs_examples_nodes'] = array(
    'template' => 'theme/example-nodes',
    'parameters' => array(),
  );
  
  $themes['angularjs_examples_nodes_list'] = array(
    'template' => 'theme/example-nodes-list',
    'parameters' => array('types' => array())  
  );

  return $themes;
}
